version: "3.10"
services:
  app:
    build: .
    ports:
      - 8000:8000
    volumes:
      - .:/healthyai
    image: application:healthy
    container_name: nutriplate_container
    command: gunicorn backend.wsgi:application --bind 0.0.0.0:8000 
