# Generated by Django 4.2.10 on 2024-02-14 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapp', '0002_alter_dietrecommendation_physical_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dietrecommendation',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10),
        ),
        migrations.AlterField(
            model_name='dietrecommendation',
            name='physical_activity',
            field=models.CharField(choices=[('Sedentray', 'Sedentray'), ('LightlyActive', 'LightlyActive'), ('ModeratelyActive', 'ModeratelyActive'), ('ExtremelyActive', 'ExtremelyActive')], max_length=50),
        ),
    ]
