# Generated by Django 4.2.10 on 2024-02-15 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_onetimepassword'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OneTimePassword',
        ),
    ]
