# Generated by Django 4.2 on 2024-02-16 09:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('serviceapp', '0003_alter_dietrecommendation_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dietrecommendation',
            name='goal',
            field=models.CharField(choices=[('WeightLoss', 'WeightLoss'), ('WeightGain', 'WeightGain'), ('MaintainWeight', 'MaintainWeight')], max_length=100),
        ),
        migrations.AlterField(
            model_name='dietrecommendation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dietRecommendations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='FoodImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dietRecommendation', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
